[hooks]
enter = "mise install --quiet"

[env]
COMPOSE_DB = ".docker/dev-stacks/postgresql/compose.yml"
COMPOSE_REDIS = ".docker/dev-stacks/redis/compose.yml"
COMPOSE_MONITORING = ".docker/dev-stacks/monitoring/compose.yml"
COMPOSE_FULL = ".docker/compose/full-stack.yml"
