#!/usr/bin/env bash
#MISE description="Stop and remove full stack containers (services + infra)"
#MISE alias="sd"
#MISE alias="down"
docker compose -f "$COMPOSE_DB" -f "$COMPOSE_REDIS" -f "$COMPOSE_MONITORING" -f "$COMPOSE_SERVICES_GENERATED" --profile infra --profile services --profile infra-ui --profile monitoring down --remove-orphans
