#!/usr/bin/env bash
#MISE description="Bootstrap project for first run (env, repos, keys, infra)"
#MISE alias="setup"
mise run setup:init-env
mise run repo:clone
mise run setup:rotate-keys
mise run setup:set-dev-env
# mise run stack:up
